apiVersion: v2
name: hub-and-spoke-dns-operator
description: A Helm chart for the Hub and Spoke DNS Kubernetes DNS Operator
type: application
version: 0.1.5
appVersion: 0.1.5
maintainers:
  - name: Marcus Aleks
    email: marcus@aleksand.com
    url: https://github.com/marcus1aleksand
